import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Footer, Header } from "@/components";
import PropTypes from "prop-types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sangtiyaans",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Header />
            <main>{children}</main>
          <Footer/>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
    children: PropTypes.node.isRequired
}