import "../globals.css";
import { Footer, Header } from "@/components";
import PropTypes from "prop-types";


export const metadata = {
  title: "Brahmastra",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <main className="layout-main">{children}</main>
      <Footer />
    </>
  );
}

RootLayout.propTypes = {
    children: PropTypes.node.isRequired
}