import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ThemeProvider } from "next-themes";
import PropTypes from "prop-types";
import ClientShell from "./ClientShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  preload: false,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: false,
});


export const metadata = {
  title: "Portfolio",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <ThemeProvider attribute="data-theme" defaultTheme="dark">
          <Providers>
            <ClientShell>
              <main>{children}</main>
            </ClientShell>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}


RootLayout.propTypes = {
  children: PropTypes.node.isRequired
};
