import { PlainHeader } from "@/components";
import PropTypes from "prop-types";

export const metadata = {
  title: "Brahmastra",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
      <main>
        <PlainHeader />
        {children}</main>
  );
}

RootLayout.propTypes = {
    children: PropTypes.node.isRequired
}