import PropTypes from "prop-types";

export const metadata = {
  title: "Sangtiyaans",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
      <main>{children}</main>
  );
}

RootLayout.propTypes = {
    children: PropTypes.node.isRequired
}